### ISSUE TITLE
Allow precision to be a different unit than wrapped type

### ISSUE THREAD

**Issue by ZevEisenberg** [ZevEisenberg/CloseEnough#3]
When comparing two `Date`s, the precision value should be a `TimeInterval`. This is not currently possible because the precision uses the same generic as the wrapped value. It might be possible to split them into two generics, with some convenience stuff for if they're equal.

This also applies for vectors, where a difference value could be expressed as either a vector or a scalar (and the user would probably want to be able to choose which one to use).

Also, not sure if we want to add Date as a built-in supported type, but probably?

**Comment by ZevEisenberg** [comment]
~`CLLocationCoordinate2D` is another good candidate, where the difference would be in meters.~ never mind, you can't diff those directly. You have to go through a `CLLocation`, and that brings along a bunch of baggage like accuracy and timestamps that would probably differ per project, so a conformance should be left up to the user if they want that.

**Comment by jbrayton** [comment]
This is fantastic!
